import { IMovie } from "../interface/movie.interface";

export const movies: IMovie[] = [
  {
    title: "Sulphur Springs",
    cnTitle: "硫磺泉",
    img: "./assets/images/sulphur.jpeg",
    description:
      "《硫磺泉鎮的秘密》是迪士尼在2021年推出的原創兒童影集，故事講述葛里芬坎貝爾跟著家人搬到硫磺泉鎮的特萊蒙旅館，傳說這間旅館因為一位女孩失蹤被傳鬧鬼。",
    genres: [
      "Drama",
      "Mystery",
      "Time travel",
      "奇幻",
      "科幻",
      "兒童",
      "硫磺泉鎮的秘密",
      "神秘",
      "劇集",
    ],
  },
  {
    title: "Loki",
    cnTitle: "洛基",
    img: "./assets/images/loki.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "洛奇",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendger",
      "復仇者",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "索爾",
      "辛普森家庭",
      "俠",
    ],
  },
  {
    title: "Simpson The Good, the Bart, and the Loki",
    cnTitle: "辛普森家庭：好人、霸子和洛基",
    img: "./assets/images/simpsons.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendger",
      "復仇者",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "索爾",
      "辛普森家庭",
      "simpson",
      "俠",
    ],
  },
  {
    title: "Thor: Ragnarok",
    cnTitle: "雷神奇俠3：諸神黃昏",
    img: "./assets/images/thor3.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "洛基",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendger",
      "復仇者",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神3",
      "索爾",
      "汙 俠",
    ],
  },
  {
    title: "Thor: The Dark World",
    cnTitle: "雷神奇俠：黑暗世界",
    img: "./assets/images/thor2.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "洛基",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendger",
      "復仇者",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
    ],
  },
  {
    title: "Thor",
    cnTitle: "雷神奇俠",
    img: "./assets/images/thor1.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "洛基",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendger",
      "復仇者",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
    ],
  },
  {
    title: "The Avengers",
    cnTitle: "復仇者聯盟",
    img: "./assets/images/avengers1.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "洛基",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendger",
      "復仇者",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
    ],
  },
  {
    title: "Avengers: Infinity War",
    cnTitle: "復仇者聯盟：無限之戰",
    img: "./assets/images/avengers3.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "洛基",

      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendgers3",
      "avendger",
      "復仇者",
      "無限之戰",
      "infinity",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
    ],
  },
  {
    title: "Avengers: Endgame",
    cnTitle: "復仇者聯盟4：終局之戰",
    img: "./assets/images/avengers4.png",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "loki",
      "洛奇",
      "洛基",
      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendgers4",
      "avendger",
      "復仇者",
      "終局之戰",
      "infinity",
      "endgame",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
    ],
  },
  {
    title: "Gifted",
    cnTitle: "天賦的禮物",
    img: "./assets/images/gifted.jpeg",
    description:
      "在漫威影業充滿激烈打鬥場面的間諜驚悚片《黑寡婦》中，黑寡婦必須面對她過去的間諜身份以及她成為復仇者之前的一段破裂關係。",
    genres: [
      "Drama",
      "Mystery",
      "Time travel",
      "劇集",
      "神秘",
      "天才少女",
      "動作",
      "冒險",
    ],
  },
  {
    title: "Guerra De Los Clones",
    cnTitle: "星際大戰複製人之戰",
    img: "./assets/images/guerra.jpeg",
    description:
      "洛基在《復仇者聯盟4：終局之戰》偷走宇宙魔方後，來到時間變異管理局。",
    genres: [
      "Mystery",
      "Time travel",
      "Star Wars",
      "Guerra Clones",
      "魔幻",
      "科幻",
      "動作",
      "冒險",
      "克隆战争",
      "星際大戰",
      "複製人之戰",
      "starwar",
      "star",
      "星球",
      "星際",
    ],
  },
  {
    title: "Juegos Mentales",
    cnTitle: "心理遊戲",
    img: "./assets/images/juegos.jpeg",
    description:
      "在漫威影業充滿激烈打鬥場面的間諜驚悚片《黑寡婦》中，黑寡婦必須面對她過去的間諜身份以及她成為復仇者之前的一段破裂關係。",
    genres: ["Drama", "Mystery", "Time travel"],
  },
  {
    title: "Wanda Vision",
    cnTitle: "溫黛與幻視",
    img: "./assets/images/wanda-vision.jpeg",
    description:
      "迪士尼 （Disney）出品，高科技的影片將你帶入數字化的世界。革命性的視覺效果，超乎你的想像力。在勇敢的女戰士柯拉的幫助下，父子在不可思議的網路世界裡展開冒險，發起了正義與邪惡的終極對戰。",
    genres: [
      "loki",
      "洛奇",
      "洛基",
      "Drama",
      "Mystery",
      "Science Fiction",
      "Sitcom",
      "Psychological Thriller",
      "Superhero",
      "marvel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "劇集",
      "動作",
      "冒險",
      "旺达幻视",
      "幻視",
      "Wanda",
      "溫黛",
      "Vision",
      "avendgers",
      "avendgers4",
      "avendger",
      "復仇者",
      "終局之戰",
      "infinity",
      "endgame",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
    ],
  },
  {
    title: "Hannah Montana",
    cnTitle: "汉娜·蒙塔娜",
    img: "./assets/images/mannah.jpeg",
    description:
      "《路卡的夏天》－迪士尼和皮克斯動畫工作室共同製作的原創電影－描寫一個小男孩在意大利里維埃拉的一個海濱小鎮的成長故事。但在他們嬉戲玩閙的背後卻隱藏了一個不為人知的秘密：他們是來自水底的海怪。",
    genres: ["Drama", "Mystery", "Time travel"],
  },

  {
    title: "Bambi",
    cnTitle: "小鹿斑比",
    img: "./assets/images/bambi.png",
    description:
      "斑比和它的大多数朋友一样，可能是森林里的任何一只鹿。在幼年时期，斑比眼睛睁得大大的，腿细长，性格好奇，声音尖锐。随着年龄的增长，它逐渐成熟，但即使到了成年期，它看起来仍然是一只非常年轻的小鹿，体格纤细，天真无邪。",
    genres: ["Drama", "Animation", "Adventure"],
  },

  {
    title: "Cars",
    cnTitle: "反斗車王",
    img: "./assets/images/cars.png",
    description:
      "明星赛车闪电麦昆和无与伦比的拖车梅特带着他们的友谊从水箱温泉出发，前往令人兴奋的新地方，他们前往海外参加有史以来第一届世界大奖赛，以决定世界上最快的汽车。但当梅特卷入一场有趣的冒险：国际间谍活动时，通往冠军的道路充满了许多坑洼、弯路和令人捧腹的惊喜！",
    genres: [
      "Kids & Family",
      "Comedey",
      "Adventure",
      "Animation",
      "汽车",
      "汽車總動員",
      "車",
    ],
  },

  {
    title: "Cinderella",
    cnTitle: "灰姑娘",
    img: "./assets/images/lacenicienta.png",
    description:
      "《灰姑娘》是一部流传于世界各地的民间故事，有成千上万个版本。故事的主角是一位生活在贫困中的少女，突然获得意外之财，通过婚姻登上了王位。。",
    genres: [" Fairy tale", "Childrens literature "],
  },

  {
    title: "Guardians of the Galaxy",
    cnTitle: "銀河守護隊",
    img: "./assets/images/reo.i.png",
    description:
      "一群技艺高超的罪犯在鲁莽的冒险家彼得·奎尔的率领下联手对抗一个名叫控诉者罗南的恶棍，他想借助一个神秘球体控制宇宙。",
    genres: [
      "loki",
      "洛奇",
      "洛基",

      "Drama",
      "Mystery",
      "Time travel",
      "英雄",
      "魔幻",
      "科幻",
      "神秘",

      "marvel",
      "Marvel",
      "劇集",
      "動作",
      "冒險",
      "超級",
      "avendgers",
      "avendgers4",
      "avendger",
      "復仇者",
      "終局之戰",
      "infinity",
      "endgame",
      "thor",
      "hero",
      "spuerhero",
      "spuer",
      "神",
      "雷神",
      "雷神2",
      "索爾",
      "俠",
      "银河护卫队",
      "galaxy",
      "guardians",
    ],
  },

  {
    title: "Monsters, Inc",
    cnTitle: "怪獸公司",
    img: "./assets/images/monstrer-inc.png",
    description:
      "在怪物的世界里，最好的朋友 Sulley 和 Mike 在一家能源公司工作，工作内容是吓唬孩子。然而，一个人类女孩的出现极大地扰乱了他们的生活。",
    genres: [
      "Comedy",
      "Animation",
      "Adventure",
      "Family",
      "家庭",
      "冒險",
      "怪兽公司",
      "動畫",
      "卡通",
      "兒童",
      "幻科",
      "奇幻",
      "怪獸",
      "monster",
    ],
  },

  {
    title: "Finding Nemo",
    cnTitle: "海底奇兵",
    img: "./assets/images/nemo.png",
    description:
      "儿子在大堡礁被绑架并被送往悉尼后，温顺的小丑鱼马林在一条健忘的鱼的帮助下，踏上了将儿子带回家的旅程。",
    genres: [
      "Comedy",
      "Animation",
      "Adventure",
      "Family",
      "家庭",
      "冒險",
      "海底",
      "動畫",
      "卡通",
      "兒童",
      "幻科",
      "奇幻",
      "海底總動員",
      "海底总动员",
      "nemo",
      "fish",
    ],
  },

  {
    title: "Star Wars",
    cnTitle: "星球大战",
    img: "./assets/images/eldespertar.png",
    description:
      "《星球大战》是乔治·卢卡斯创作的美国史诗太空歌剧媒体系列，从 1977 年的同名电影开始，迅速成为全球流行文化现象。",
    genres: [
      "Mystery",
      "Time travel",
      "Star Wars",
      "Guerra Clones",
      "魔幻",
      "科幻",
      "動作",
      "冒險",
      "克隆战争",
      "星際大戰",
      "複製人之戰",
      "starwar",
      "star",
      "星球",
      "星際",
    ],
  },

  {
    title: "Hannah Montana",
    cnTitle: "樂壇Teen后",
    img: "./assets/images/mannah.jpeg",
    description:
      "麦莉·斯图尔特是一名普通的少女，她假扮为著名流行歌手汉娜·蒙塔娜，过着双重生活，并不断试图向公众隐瞒她的真实身份。",
    genres: [
      ,
      "Comedy",
      "Family",
      "Music",
      "汉娜·蒙塔娜",
      "漢娜",
      "孟漢娜",
      "劇集",
      "家庭",
      "音樂",
    ],
  },

  {
    title: "Aladdin",
    cnTitle: "阿拉丁",
    img: "./assets/images/aladdin.png",
    description:
      "阿拉丁，一个普通的小偷，爱上了茉莉公主，但他不能娶她，因为他不是王子。贾法尔，一个怀有不可告人的目的的皇家宰相，请求阿拉丁帮助他找回一盏神灯。",
    genres: [
      ,
      "Comedy",
      "Adventure",
      "Family",
      "Fantasy",
      "Musical",
      "Romance",
      "劇集",
      "家庭",
      "音樂",
      "卡通",
      "動畫",
      "魔幻",
      "科幻",
      "動作",
      "冒險",
    ],
  },

  {
    title: "A Wrinkle in Time",
    cnTitle: "時間的皺摺",
    img: "./assets/images/vaiaje-timpo.png",
    description:
      "在寻找科学突破的过程中，梅格的父亲消失在太空的另一个空间中。三个奇怪的生物派梅格、她的兄弟查尔斯和朋友卡尔文去寻找他。",
    genres: [
      ,
      "Adventure",
      "Drama",
      "Family",
      "Fantasy",
      "时间的皱折",
      "時間的皺摺",
      "時間",
      "time",
      "家庭",
      "魔幻",
      "科幻",
      "動作",
      "冒險",
    ],
  },
];
